import { Inter } from "next/font/google";
import "./globals.css";
import Headers from "./components/Headers";
import Footer from "./components/Footer";
import { CartProvider } from "./context/cartContext";
import { AuthProvider } from "./context/AuthContext";
import Head from "next/head"; // Importa el componente Head de Next.js

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <CartProvider>
            <Headers />
            <Head>
              <link rel="icon" href="/logoPiza.png" />
        
            </Head>
            {children}
            <Footer />
          </CartProvider>
        </AuthProvider>
      </body>
    </html>
  );
}